### ISSUE TITLE
[Bug] 玩家拥有操作员权限时启用freecamera会直接变为旁观者模式且再次切换时无法回到原来的游戏模式

### ISSUE THREAD

**Issue by DJRsiri** [GroupMountain/FreeCamera#12]
如题。
----重现操作----
玩家权限等级：4
cmd：/fc
自由视角已启用（玩家游戏模式被更改成旁观者，本体未显示）
cmd：/fc
自由视角已启用（玩家游戏模式仍是旁观者，此时本体已显示）
cmd：/fc
自由视角已禁用（玩家游戏模式仍是旁观者，本体消失同时回到本体所在位置）
----END----
fc版本0.12.0
bds版本 1.20.81-1.671+a9081c5 with LeviLamina-0.12.1+0e8f1f073

**Comment by KobeBryant114514** [comment]
有空我再看看吧，1.20.80因为mojang改了相关数据包，没具体测试
