### ISSUE TITLE
 提交问题

### ISSUE THREAD

**Issue by MoonlightUU** [GroupMountain/FreeCamera#13]
声明 : 提出此问题只是为了支持作者 意思是有人正在使用你的作品支持你, 不支持, 不回应, 个人觉得会导致社区生态没落;
1, op重复使用fc命令会导致传送到本体位置, 模式被 真 修改为旁观;
2, 待验证? 玩家使用这个灵魂出窍期间重生后, 附近有苦力怕炸掉的方块会恢复成假方块
3, 待验证? 与LeviAntiCheat 冲突 (已被检测到使用: IllegalMovement, mismatch distance)

**Comment by DJRsiri** [comment]
好像是第一次使用fc就变（成旁观）了，第二次才是真的进入freecamera状态，而且不用gamemode切不回来。我在带管理员权限的生存模式下测试的。实测无权限时不会出现被修改游戏模式为旁观
-----与当前讨论的无关内容-----
这边给个建议：是不是假方块可以打开bds移动检测过去踩，会被拉回弹或者直接拉进方块的就是假方块

**Comment by yufengya0420** [comment]
> 好像是第一次使用fc就变（成旁观）了，第二次才是真的进入freecamera状态，而且不用gamemode切不回来。我在带管理员权限的生存模式下测试的。实测无权限时不会出现被修改游戏模式为旁观
> -----与当前讨论的无关内容-----
> 这边给个建议：是不是假方块可以打开bds移动检测过去踩，会被拉回弹或者直接拉进方块的就是假方块

我生存op用了这么长时间暂未出现你们说的情况，目前一切正常

**Comment by KobeBryant114514** [comment]
> 声明 : 提出此问题只是为了支持作者 意思是有人正在使用你的作品支持你, 不支持, 不回应, 个人觉得会导致社区生态没落; 1, op重复使用fc命令会导致传送到本体位置, 模式被 真 修改为旁观; 2, 待验证? 玩家使用这个灵魂出窍期间重生后, 附近有苦力怕炸掉的方块会恢复成假方块 3, 待验证? 与LeviAntiCheat 冲突 (已被检测到使用: IllegalMovement, mismatch distance)

问题1我会尝试修复。
问题2是LAC的客户端区块缓存问题，正在讨论解决方案。
问题3理论上无关系。

**Comment by KobeBryant114514** [comment]
> 好像是第一次使用fc就变（成旁观）了，第二次才是真的进入freecamera状态，而且不用gamemode切不回来。我在带管理员权限的生存模式下测试的。实测无权限时不会出现被修改游戏模式为旁观 -----与当前讨论的无关内容----- 这边给个建议：是不是假方块可以打开bds移动检测过去踩，会被拉回弹或者直接拉进方块的就是假方块

需要op才能复现吗

**Comment by DJRsiri** [comment]
> > 好像是第一次使用fc就变（成旁观）了，第二次才是真的进入freecamera状态，而且不用gamemode切不回来。我在带管理员权限的生存模式下测试的。实测无权限时不会出现被修改游戏模式为旁观 -----与当前讨论的无关内容----- 这边给个建议：是不是假方块可以打开bds移动检测过去踩，会被拉回弹或者直接拉进方块的就是假方块
> 
> 需要op才能复现吗

是的。

**Comment by KobeBryant114514** [comment]
> > > 好像是第一次使用fc就变（成旁观）了，第二次才是真的进入freecamera状态，而且不用gamemode切不回来。我在带管理员权限的生存模式下测试的。实测无权限时不会出现被修改游戏模式为旁观 -----与当前讨论的无关内容----- 这边给个建议：是不是假方块可以打开bds移动检测过去踩，会被拉回弹或者直接拉进方块的就是假方块
> > 
> > 需要op才能复现吗
> 
> 是的。

难绷，估计是1.20.80开始因为切游戏模式的数据包更改，客户端有op现在会强制同步服务端模式，估计得把这个包拦掉。
