### ISSUE TITLE
[Feature]:希望与LLMoney和Money计分板对接

### ISSUE THREAD

**Issue by BensonChen2456** [GroupMountain/FreeCamera#18]
感谢GroupMountain开发了众多好用的插件
但是此插件还有许多值得改进的地方
玩家容易依赖此插件的功能 所以我希望能对接LLMoney和Money计分板 这样可以限制玩家使用的频率和次数 可以在配置文件里自定义
祝Group Mountain团队：
蒸蒸日上 插件永无bug
谢谢！

**Comment by BensonChen2456** [comment]
Emmmmmm没人理我吗

**Comment by KobeBryant114514** [comment]
不是，这个插件和计分板以及llmoney有啥关系？

**Comment by Zhongzi8972** [comment]
自己写一个插件去限制/fc的命令使用次数，此功能与本插件无关

**Comment by Zhongzi8972** [comment]
不过谢谢你的祝福哦OvO
